FLUSH PRIVILEGES;
CREATE USER 'appUser'@'localhost' IDENTIFIED BY 'appPass';
GRANT ALL PRIVILEGES ON *.* TO 'appUser'@'localhost' WITH GRANT OPTION;
CREATE USER 'appUser'@'%' IDENTIFIED BY 'appPass';
GRANT ALL PRIVILEGES ON *.* TO 'appUser'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;